# Generated by Django 5.1.1 on 2024-09-24 06:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(default='', upload_to='images'),
        ),
        migrations.AlterField(
            model_name='products',
            name='disc_price',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='flat',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='products',
            name='price',
            field=models.IntegerField(),
        ),
    ]
