# Generated by Django 5.1.1 on 2024-09-25 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0006_products_trending'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='top_catogery',
            field=models.BooleanField(default=False),
        ),
    ]
