# Generated by Django 5.1.1 on 2024-09-25 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0007_category_top_catogery'),
    ]

    operations = [
        migrations.AddField(
            model_name='brand',
            name='top_catogery',
            field=models.BooleanField(default=False),
        ),
    ]
