# Generated by Django 5.1.1 on 2024-09-25 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0009_alter_products_disc_price_alter_products_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='storage',
            field=models.CharField(blank=True, default='', max_length=10, null=True),
        ),
    ]
