# Generated by Django 5.1.1 on 2024-09-25 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0010_products_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='storage',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
