# Generated by Django 5.1.1 on 2024-09-26 06:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0011_alter_products_storage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='disc_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='products',
            name='flat',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
