# Generated by Django 5.1.1 on 2024-10-02 06:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0017_cart_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='products',
            old_name='catogery',
            new_name='category',
        ),
    ]
