# Generated by Django 5.1.1 on 2024-10-02 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0018_rename_catogery_products_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='products',
            name='disc_price',
            field=models.DecimalField(blank=True, decimal_places=2, default=0.0, max_digits=10, null=True),
        ),
    ]
