# Generated by Django 5.1.1 on 2024-10-07 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecommerce', '0019_alter_products_disc_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='cart',
            name='total',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
